#$ -cwd
#$ -q QUEUE
#$ -pe mpi 8
#$ -S /bin/bash

module load MegaHit/v1.1.4

# Kmer value: must be an odd number in the range 15-255. 
# Make sure that the read length is longer than the kmer value.
KMER=

# Name of the analysis. Will prefix the output filenames.
SAMPLE=

# Input files in (compressed) fastq format.
FILE1=
FILE2=

# Run the assembly analysis
megahit --k-list $KMER -1 $FILE1 -2 $FILE2 -t $NSLOTS -o $SAMPLE --out-prefix $SAMPLE --keep-tmp-files
# ... and save the assembly graph to a file.
megahit_toolkit contig2fastg $KMER ${SAMPLE}/intermediate_contigs/k${KMER}.contigs.fa > k${KMER}.fastg
